# CMSC 478 Machine Learning
## Fereydoon Vafaei
#### February 2020

<br>

## Workbook - Numpy Slicing

In this notebook, let's practice a few numpy array slicing exercises as you may encounter these practices in your assignments and projects frequently.

First, create a 1D numpy array with evenly placed integer numbers (type=np.float64) over a specified interval.

In [1]:
import numpy as np
x = np.linspace(1,10, num=10)
print(type(x))      # numpy.ndarray
print(type(x[0]))   # numpy.float64
x

<class 'numpy.ndarray'>
<class 'numpy.float64'>


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Now, there are different ways that you may want to slice this numpy array. In the following cells, see some examples.

> Let's slice the first five elements. The generic format for slicing is: `[start:stop:step]` 
Notice that indices start from `0`.
Also notice that `step` is not necessary, `default step = 1`

In [2]:
x[0:5]

array([1., 2., 3., 4., 5.])

> We can also leave the index before `:` blank. This means slice everything from the beginning till the stop index - i.e. the index after `:`, excluding `x[5]`.

In [3]:
x[:5]	    # [1,2,3,4,5]

array([1., 2., 3., 4., 5.])

In [4]:
x[4]

5.0

In [5]:
x[5]

6.0

> And similarly for slicing anything from the index before `:` till the end - this time though the slice includes `x[5]` itself.

In [6]:
x[5:]

array([ 6.,  7.,  8.,  9., 10.])

> Some more examples:

In [7]:
x[0:]	    # the entire x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
print(x[:0])      # Early stopping means the returned slice is empty!

[]


In [9]:
print(x[:-1])     # all excluding the last element

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
print(x[-1:])      # Only the last element

[10.]


In [11]:
print(x[::-1])      # all in the reversed order

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


In [12]:
print(x[0:10:2])    # step=2 : [1,3,5,7,9]

[1. 3. 5. 7. 9.]


In [13]:
print(x[::2])       # [1,3,5,7,9]

[1. 3. 5. 7. 9.]


> Kind of cool, isn't it? Now, let's try some 2D arrays.

In [14]:
# 2-dimensional np.array slicing with comma (tuple indices)
a = np.reshape(np.arange(9),(3,3)) # create a 2D array 3x3 with numbers {0..8}
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
print(a[0,:])       # first row

[0 1 2]


In [16]:
print(a[:,0])       # first column displayed horizontally

[0 3 6]


In [17]:
print(a[0:,0:1])    # first column displayed vertically (in 3 rows)

[[0]
 [3]
 [6]]


In [18]:
print(a[:3,:1])     # another way to print the first column vertically (in 3 rows)

[[0]
 [3]
 [6]]


>In general, open/close brackets, then put a comma between the two colons `[:,:]` then:
- either replace each colon with a number to get a specific row or column e.g `[2,:]` --> would return the third row,
- or specify the range of rows/cols with the colon between, e.g `[:,0:2]` --> would return the first two columns

>Let's see how it works.

In [19]:
a[:,:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
print(a[0:2,])      # first two rows, also can be written: a[0:2,:]

[[0 1 2]
 [3 4 5]]


In [21]:
print(a[1:,0:1])     # first column and all row expect first 

[[3]
 [6]]


> Sometimes though, there are "Oops!" moments, like the following. But there is "always" - wait, what?! alright at least most of the times - a "Pythonic" way to do what you want!

In [23]:
a[,0:2] 	    # invalid syntax

SyntaxError: invalid syntax (<ipython-input-23-f0611a762ed9>, line 1)

In [24]:
print(a[:3:2,:])    # first and third row (step=2)
print(a[:,0:3:2])   # first and third column (step=2)
print(a[2::-1, 0])  # first column reversed
print(a[::-1])      # this reverses the elements in each colomn, i.e. colomn-wise reverse or row-shift
print(a[::,::-1])   # this reverses the elements in each row, i.e. row-wise reverse or colomn-shift
print(a[::-1,::-1]) # this reverses both axes

[[0 1 2]
 [6 7 8]]
[[0 2]
 [3 5]
 [6 8]]
[6 3 0]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[8 7 6]
 [5 4 3]
 [2 1 0]]


>Not all np slicing tricks may work for lists!

In [25]:
b = [[0,1,2], [3,4,5]]
print(type(b))      # list
b

<class 'list'>


[[0, 1, 2], [3, 4, 5]]

In [26]:
b[:1]
b[-1]

[3, 4, 5]

In [27]:
b[:,0]            # Error: list indices must be integers or slices, not tuple

TypeError: list indices must be integers or slices, not tuple

Hope this helps! Try with your own arrays and pratice what you learned in this workbook/notebook!